import streamlit as st
import numpy as np
import tensorflow as tf
from PIL import Image
import time

# --- Page Configurations ---
st.set_page_config(
    page_title="NeuroScan AI | Brain Tumor Diagnostics",
    page_icon="🧠",
    layout="wide",
    initial_sidebar_state="expanded"
)

# --- Custom Styling for a Unique Medical Dashboard Appearance ---
st.markdown("""
    <style>
    .main-title {
        font-size: 38px;
        color: #1E3A8A;
        font-weight: 700;
        margin-bottom: 5px;
    }
    .subtitle {
        font-size: 16px;
        color: #555555;
        margin-bottom: 25px;
    }
    .metric-card {
        background-color: #F0F4F8;
        padding: 15px;
        border-radius: 10px;
        border-left: 5px solid #2563EB;
    }
    </style>
""", unsafe_allow_html=True)

# --- Sidebar Controls & Patient Metadata Generator ---
with st.sidebar:
    st.image("https://cdn-icons-png.flaticon.com/512/3004/3004458.png", width=80)
    st.markdown("### **NeuroScan AI Settings**")
    st.info("System Engine: TensorFlow v" + tf.__version__)
    
    st.markdown("---")
    st.markdown("### **📋 Patient Metadata (Simulation)**")
    patient_id = st.text_input("Patient ID", value="PT-88341")
    scan_type = st.selectbox("MRI Contrast Type", ["T1-Weighted", "T2-Weighted", "FLAIR"])
    st.caption("Metadata will be appended to the generated diagnostic report scan.")

# --- Core Model Loading Setup ---
@st.cache_resource
def load_diagnostic_engine():
    # Targets the exact model file generated by your train_model.py script
    return tf.keras.models.load_model("brain_tumor_model.h5")

# --- Main App Layout ---
st.markdown("<div class='main-title'>🧠 NeuroScan AI Workspace</div>", unsafe_allow_html=True)
st.markdown("<div class='subtitle'>Advanced Neural Network Diagnostic Workspace for Tumor Identification</div>", unsafe_allow_html=True)

try:
    model = load_diagnostic_engine()
except Exception as e:
    st.error("🚨 Core Neural Engine Not Detected! Please ensure 'brain_tumor_model.h5' has finished training and is present in your folder.")
    st.stop()

# --- Layout: Two Column Workspace Split ---
col1, col2 = st.columns([1, 1.2], gap="large")

with col1:
    st.markdown("### **1. Scan Upload & Source Material**")
    uploaded_file = st.file_uploader("Drop MRI File Here...", type=["jpg", "jpeg", "png"])
    
    if uploaded_file is not None:
        raw_image = Image.open(uploaded_file)
        st.image(raw_image, caption=f"Source File: {uploaded_file.name} | Mode: {scan_type}", use_container_width=True)
    else:
        st.write("💡 *Awaiting input file... Please drag and drop an image scan to trigger the diagnostic matrix.*")

with col2:
    st.markdown("### **2. Neural Network Telemetry Analysis**")
    
    if uploaded_file is not None:
        # Visual Processing Indicator Bar
        progress_bar = st.progress(0)
        with st.spinner("Executing Layer-by-Layer Convolutional Matrix..."):
            for percent_complete in range(100):
                time.sleep(0.005)
                progress_bar.progress(percent_complete + 1)
                
            # --- Preprocessing Pipeline ---
            # Adjust (150, 150) if your specific network was trained on a different resolution!
            target_size = (150, 150) 
            processed_img = raw_image.resize(target_size).convert("RGB")
            img_array = np.array(processed_img).astype("float32") / 255.0
            input_batch = np.expand_dims(img_array, axis=0)
            
            # --- Inference Run ---
            predictions = model.predict(input_batch)
            
        st.success("Matrix scan analysis finalized!")
        st.markdown("---")
        
        # --- Metrics & Outputs Blocks ---
        # Handle Dynamic Model Architectures (Binary Classification Output vs. Multi-class Categorical)
        if predictions.shape[1] == 1:
            raw_score = predictions[0][0]
            if raw_score > 0.5:
                verdict = "⚠️ TUMOR DETECTED"
                final_confidence = raw_score * 100
                status_color = "inverse"
            else:
                verdict = "✅ NORMAL / UNREMARKABLE"
                final_confidence = (1 - raw_score) * 100
                status_color = "normal"
        else:
            class_idx = np.argmax(predictions)
            verdict = f"MALIGNANCY TYPE INDEX: Class {class_idx}"
            final_confidence = predictions[0][class_idx] * 100
            status_color = "normal"

        # Unique Metric Container Readouts
        m_col1, m_col2 = st.columns(2)
        with m_col1:
            st.markdown(f"<div class='metric-card'><b>Diagnostic Target:</b><br><span style='font-size:20px; font-weight:bold;'>{patient_id}</span></div>", unsafe_allow_html=True)
        with m_col2:
            st.markdown(f"<div class='metric-card'><b>Calculated Confidence:</b><br><span style='font-size:20px; font-weight:bold; color:#2563EB;'>{final_confidence:.2f}%</span></div>", unsafe_allow_html=True)
            
        st.markdown("<br>", unsafe_allow_html=True)
        st.subheader("System Diagnostic Verdict")
        st.code(f"[SYSTEM VERDICT] -> {verdict}", language="bash")
        
        # Interactive UI Breakdown Component
        with st.expander("🔬 View Raw Mathematical Confidence Array"):
            st.write("This array represents the activation strength of the network's final Softmax/Sigmoid classification output layer:")
            st.json({"output_tensor_values": predictions.tolist()})
            
    else:
        st.warning("Awaiting file submission in the left partition column to initialize automated diagnostics telemetry.")